#!/bin/bash

ip1=8.8.8.8
ip2=8.8.8.8
ip3=8.8.8.8

while :
do
  num=0
  for ip in $ip1 $ip2 $ip3
  do
    num=$((num + 1))
    str=`ping -W 1 -c 1 $ip 2>/dev/null | sed -nE 's/.*time=([0-9.]+).*/\1/p' | tr -d '\n'`
    printf "(%s) %-6s" $num $str
  done
  echo
  sleep 1
done
